### ISSUE TITLE
Compose key not supported in nimf

### ISSUE THREAD

**Issue by mxa** [cogniti/nimf#33]
Since installing nimf, the compose key is not working any more. I need that to write other languages with a Korean keyboard.

**Comment by cogniti** [comment]
Hello.
What does the compose key mean?

**Comment by cogniti** [comment]
Hello.
What does the compose key mean?

**Comment by cogniti** [comment]
I understand Chinese, Japanese, Korean and English. You can write in your native language.

**Comment by mxa** [comment]
with the [compose key](https://en.wikipedia.org/wiki/Compose_key) I can type an `ö` by typing the sequence: `compose key` then `"`, then `o`. I deactivated CapsLock and chose the CapsLock key as my compose key.
![composekey](https://cloud.githubusercontent.com/assets/1220707/21421638/3a3bf3ac-c834-11e6-9832-3184d24cd60d.png)

**Comment by cogniti** [comment]
Okay. I will test it in January or February.

**Comment by mxa** [comment]
Could you confirm that you have the same issue on your system? I'd like to be certain that it's a nimf issue, and not a Linux mint 18.1 update issue or something else.

**Comment by mxa** [comment]
FYI Here is a similar bug in XIM: https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1573755

**Comment by cogniti** [comment]
Applied gtk_im_context_simple https://github.com/cogniti/nimf/commit/cd5d94193ff002fbf374dbe842da1dab82cec336

**Comment by mxa** [comment]
Cool. thanks. When Is this change going to arrive in the PPA, so I can test it?

**Comment by cogniti** [comment]
Sorry, I have no plans to upload into PPA.

**Comment by mxa** [comment]
Oh, that's sad. Why? ppa:hodong/testing

**Comment by cogniti** [comment]
I don't have time and I have no obligation to provide packages.

**Comment by mxa** [comment]
For the record: There is a ppa with nimf daily for anyone that is finding this by searching: `ppa:elementary-os/daily`

**Comment by cogniti** [comment]
For Ubuntu 16.10, You can download at

https://code.launchpad.net/~elementary-os/+recipe/nimf-daily

**Comment by mxa** [comment]
I get `Dependency is not satisfiable: libgtk-3-0 (>= 3.21.4)` on this deb.

**Comment by cogniti** [comment]
What is your Linux distribution?

**Comment by mxa** [comment]
Linux Mint 18.1 Cinnamon 64bit

**Comment by cogniti** [comment]
Linux Mint 18.1 is based on Ubuntu 16.04.
The nimf needs `librime >= 1.2.9`.
However, Ubuntu 16.04 contains the librime 1.2.
Dependency issue is resolved since Ubuntu 16.10.

To avoid this problem in Ubuntu 16.04, compile nimf after changing 3 lines.

Delete the line
`PKG_CHECK_MODULES(NIMF_RIME_DEPS, [rime> = 1.2.9 $ LIBNIMF_REQUIRES])` from `nimf/configure.ac`,
In `nimf/modules/engines/Makefile.am`, delete only `nimf-rime`, not line deletion.
Delete `librime-dev (> = 1.2.9)` line from `nimf/debian/control`.

## How to build deb package

First of all, install `devscripts`, `build-essential`.

```
username:~$ sudo apt install devscripts build-essential
```

After installing `devscripts`, `build-essential` perform the following commands.

```
username:~$ cd
username:~$ mkdir tmp-build
username:~$ cd tmp-build
username:~/tmp-build$ wget https://github.com/cogniti/nimf/archive/2017.02.21.tar.gz
username:~/tmp-build$ tar zxf 2017.02.21.tar.gz
username:~/tmp-build$ cd nimf-2017.02.21
username:~/tmp-build/nimf-2017.02.21$ dpkg-checkbuilddeps
```

You may see something like:

> dpkg-checkbuilddeps: Unmet build dependencies: some-package1 some-package2 ...

Install all missing dependencies and perform the following commands.

```
username:~/tmp-build/nimf-2017.02.21$ debuild
username:~/tmp-build/nimf-2017.02.21$ cd ..
username:~/tmp-build$ ls
2017.02.21.tar.gz              nimf_2017.02.21_amd64.deb
nimf-2017.02.21                nimf_2017.02.21.dsc
nimf_2017.02.21_amd64.build    nimf_2017.02.21.tar.xz
nimf_2017.02.21_amd64.changes  nimf-dev_2017.02.21_amd64.deb
```

As above mentioned, make the package yourself. Otherwise, request your Linux
distribution to package Nimf.

**Comment by cogniti** [comment]
There is a financial loss to me as much as I spend time here.
However, I have created PPA https://launchpad.net/~hodong/+archive/ubuntu/nimf

```
sudo add-apt-repository ppa:hodong/nimf
sudo apt update
sudo apt install nimf
im-config -n nimf
```

https://launchpad.net/~hodong/+archive/ubuntu/nimf/+files/nimf_2017.03.17.1~xenial_amd64.deb

nimf (2017.03.17.1~xenial) xenial; urgency=medium
  * nimf-rime removed because of the dependency

**Comment by bagjunggyu** [comment]
님프에서 일본어와 중국어는 이제 알파 버전을 벗어난 것인가요?

**Comment by cogniti** [comment]
@bagjunggyu 중국어, 일본어는 아직 알파 단계입니다. 따로 이슈 올려주세요.

**Comment by bagjunggyu** [comment]
네
