### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by baimafeima** [cogniti/nimf#41]
Could you add versioned tarball releases here on GitHub?

**Comment by cogniti** [comment]
Hello.
The master branch is almost a release version.

**Comment by baimafeima** [comment]
@cogniti I would need versioned tarballs in order to suggest it for possible iclusion into the Solus repositories.

**Comment by cogniti** [comment]
I am sorry. Creating tags is too cumbersome.
You can find the version information in `configure.ac` and ` debian/changelog
` files of the last commit.

**Comment by baimafeima** [comment]
Tagging releases would have several advantages and allow for the changelog to be directly visible in your GitHub releases. This would also increase transparency for potential users, allow to receive updates when a new version is released, i.e. version updates can be tracked, and tagged releases are often considered a prerequisite for having your software added to the repositories of many Linux-based operating systems. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by cogniti** [comment]
Thank you for your information.
Whenever I push commits, I release Nimf.
Therefore tags increase too much.
And tagging release is too cumbersome because I haven't even enough time to sleep.

Nimf is already transparent.
You can see all codes, commit history, changelog and changes directly.

https://github.com/cogniti/nimf/blob/master/debian/changelog
https://github.com/cogniti/nimf/blob/master/NEWS (symbolic link)
https://github.com/cogniti/nimf/commits/master

Also you can receive updates.
See https://github.com/cogniti/nimf/subscription
![screenshot from 2017-09-07 21-20-35](https://user-images.githubusercontent.com/17453239/30163140-d158f712-9412-11e7-8660-c26324d1d49e.png)

Release date is version name, version name is release date.
Therefore you can easily track version updates.
https://github.com/cogniti/nimf/commits/master/debian/changelog
